### ISSUE TITLE
The variation of g_i seems not to be used.

### ISSUE THREAD

**Issue by chengjianhong** [WeiChengTseng/PCGrad#9] opened 2021-03-27 11:19 UTC
Hi, there may be a major problem that `g_i ` doesn't be used to modify `pc_grad` according to the code. 

 ```
 def _project_conflicting(self, grads, has_grads, shapes=None):
        shared = torch.stack(has_grads).prod(0).bool()
        pc_grad, num_task = copy.deepcopy(grads), len(grads)
        for g_i in pc_grad:
            random.shuffle(grads)
            for g_j in grads:
                g_i_g_j = torch.dot(g_i, g_j)
                if g_i_g_j < 0:
                    g_i -= (g_i_g_j) * g_j / (g_j.norm()**2)
        merged_grad = torch.zeros_like(grads[0]).to(grads[0].device)

        merged_grad[shared] = torch.stack([g[shared]
                                           for g in pc_grad]).mean(dim=0)
        merged_grad[~shared] = torch.stack([g[~shared]
                                            for g in pc_grad]).sum(dim=0)
        return merged_grad

```

**Comment by chengjianhong** [comment] 2021-03-28 02:15
Sorry, It's my fault. That is right!

**Comment by WeiChengTseng** [comment] 2021-03-28 03:10
Since the problem is solved, I close the issue.

**Closed as completed** 2021-03-28 03:10 UTC
